server:
  port: 8081
spring:
  datasource:
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ganyihan
    url: jdbc:mysql://127.0.0.1:3306/lecture_training
  devtools:
    livereload:
      enabled: false