server:
  port: 8082
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20M

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  # 数据库驱动
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/business_db?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT
    username: root
    password: Cyw062014@
#
#  # 数据库驱动
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/summer?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT
#    username: Soft
#    password: 123456



#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  # 配置xml文件中用到的实体的路径
  type-aliases-package: com.example.equipmentmanagementspring.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl