server:
  # 统一的访问入口
  port: 9999
spring:
  application:
    name: nacos-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 120.26.73.133:8848
    gateway:
      discovery:
        locator:
          enabled: true #开启表示根据微服务名称映射，就是微服务名称拼接到url中可以直接访问，但是不推荐这么使用 容易暴露微服务 默认false，开启后可以通过ip:port/服务名称/接口地址进行服务转发
      enabled: true #默认开启网关true，关闭网关false
      # 这里就是配置微服务的访问，可以实现负载均衡等功能
      routes:
        - id: user-service #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: http://localhost:8082  #匹配后提供服务的路由地址
          predicates:
            - Path=/user-service/**  #断言，路径相匹配的进行路由转发
        - id: stock-service
          uri: http://localhost:8083
          predicates:
            - Path=/stock-service/**